# -*- coding: utf-8 -*-
"""5_flower_classification_using_pretrained_embedding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YbboNTwp6wKYPwxuoJhKiXvR8XM1SFeD
"""

import wandb
from wandb.integration.keras import WandbMetricsLogger

import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow import keras

sweep_config = {

    'method'   : 'grid',
    'metric'   : {
        'name' : 'val_accuracy',
        'goal' : 'maximize'
                 },
    'parameters' : {
        'batch_size'    : {'values': [8]},
        'learning_rate' : {'values': [0.0001]},
        'img_size'      : {'values': [128]},
        'epochs'        : {'values': [60]},
        'experiment'    : {'values': ['transfer_learning']}
    }
}

sweep_id = wandb.sweep(sweep_config, project="5_Flowers_Classification_Transfer_Learning1")

import kagglehub

# Download latest version
path = kagglehub.dataset_download("kausthubkannan/5-flower-types-classification-dataset")

print("Path to dataset files:", path)

import os
print(os.listdir(path))
new_path = os.path.join(path, "flower_images")
print(os.listdir(new_path))

import pandas as pd
from sklearn.model_selection import train_test_split
import os

image_paths = []
labels = []

# Define CLASS_NAMES here so it's accessible
CLASS_NAMES = ['Lilly', 'Tulip', 'Sunflower', 'Lotus', 'Orchid']

# Populate image_paths and labels
for class_name in CLASS_NAMES:
    class_dir = os.path.join(new_path, class_name)
    if os.path.exists(class_dir):
        for img_name in os.listdir(class_dir):
            if img_name.lower().endswith(('.png', '.jpg', '.jpeg')):
                image_paths.append(os.path.join(class_dir, img_name))
                labels.append(class_name)

if not image_paths:
    print("No image files found. Please verify the dataset structure and 'new_path'.")
else:
    df = pd.DataFrame({'filename': image_paths, 'label': labels})

    # Split into training and evaluation sets
    train_df, eval_df = train_test_split(df, test_size=0.2, random_state=42, stratify=df['label'])

    # Save to CSV files in the current working directory
    train_csv_path = 'train_set.csv'
    eval_csv_path = 'eval_set.csv'
    train_df.to_csv(train_csv_path, index=False, header=False)
    eval_df.to_csv(eval_csv_path, index=False, header=False)

    print(f"Generated training CSV: {train_csv_path} ({len(train_df)} samples)")
    print(f"Generated evaluation CSV: {eval_csv_path} ({len(eval_df)} samples)")

    print("\nTrain DataFrame Head:")
    display(train_df.head())
    print("\nEval DataFrame Head:")
    display(eval_df.head())

def train():
  with wandb.init() as run:
    config = wandb.config

    # Constants
    IMG_HEIGHT = 128
    IMG_WIDTH = 128
    IMG_CHANNELS = 3
    CLASS_NAMES = tf.constant(['Lilly', 'Tulip', 'Sunflower', 'Lotus', 'Orchid'])



    def read_and_decode(filename, resize_dims):
        img_bytes = tf.io.read_file(filename)
        img = tf.image.decode_jpeg(img_bytes, channels=IMG_CHANNELS)
        img = tf.image.convert_image_dtype(img, tf.float32)
        img = tf.image.resize(img, resize_dims)
        return img

    def parse_csvline(csv_line):
        record_default = ["", ""]
        filename, label_string = tf.io.decode_csv(csv_line, record_default)

        img = read_and_decode(filename, [IMG_HEIGHT, IMG_WIDTH])

        # Convert label string to an integer index
        label = tf.where(tf.equal(CLASS_NAMES, label_string))[0, 0]

        return img, label

    # Define datasets
    train_dataset = (
        tf.data.TextLineDataset(os.path.join(os.getcwd(), train_csv_path))
        .skip(1) # Skip header if present, but we generated without header
        .map(parse_csvline, num_parallel_calls=tf.data.AUTOTUNE)
        .batch(config.batch_size)
        .prefetch(tf.data.AUTOTUNE)
    )

    eval_dataset = (
        tf.data.TextLineDataset(os.path.join(os.getcwd(), eval_csv_path))
        .skip(1) # Skip header if present, but we generated without header
        .map(parse_csvline, num_parallel_calls=tf.data.AUTOTUNE)
        .batch(config.batch_size)
        .prefetch(tf.data.AUTOTUNE)
    )
    #Base_model
    base_model = tf.keras.applications.MobileNetV2(
    input_shape=(128, 128, 3),
    include_top=False,  # Remove classification head
    weights="imagenet"  # Load weights trained on ImageNet
    )
    base_model.trainable = False

    #architecture
    model = tf.keras.Sequential([
    base_model,
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(5, activation='softmax')  # 5 classes: daisy, dandelion, etc
    ])


    model.compile(
          optimizer=keras.optimizers.Adam(learning_rate=config.learning_rate),
          loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
          metrics=["accuracy"]
      )

    model.fit(
      train_dataset,
      validation_data=eval_dataset,
      epochs=config.epochs,
      callbacks=[WandbMetricsLogger(log_freq=5)]
      )

wandb.agent(sweep_id, function=train)